import img from '../../../../public/Image/homemade-beef-burger-caramelized-onion-bacon-and-beer-e1627971449244.jpg'

export default function PrivacyPolicy(){
     return(
          <div>

            <div className='pt-10'>


<div>
     <div className='relative'>
          <img src={img} alt="" className='h-100 w-full'/>
     </div>
     <div className='absolute flex justify-center items-center left-0 right-0 top-50  text-center'>
          <p className='font-black text-2xl md:text-3xl xl:text-4xl text-white uppercase'>Privacy policy | kawsar.restaurent</p>
     </div>
</div>


<div className='bg-white p-5 flex flex-col gap-10'>
 
 <p className='text-gray-500'>
     This policy explains how we, kawsar.restaurent, a brand of <b>https://kawsar-restaurant-projects.netlify.app/</b>, use your personal information which you provide to us when using our service, including but not limited to our website and mobile applications (apps).
 </p>

<b>What information we collect about you?</b>

<p className='text-gray-500 capitalize'>
  We collect personal information from you when you order goods or services from us or use our website. We also collect information when you complete any customer survey. Website usage information may also be collected using cookies.   
</p>


<b>Cookies and Google Analytics</b>
<p className='text-gray-500 capitalize'>
   Cookies are small text files that are placed on your computer by websites that you visit. They are widely used in order to make websites work, or work more efficiently, as well as to provide information to the owners of the site.  
</p>


<p className='text-gray-500 capitalize'>
This website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files saved on your computer, to help the website analyze how you use the site. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States. If this website anonymizes IP addresses, your IP address will be truncated by Google within a EU member state or other EEA state before being transmitted to the US. Only in exceptional situations will your full IP address be transmitted to Google servers in the United States and truncated there. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above. You can also prevent Google from collecting information (including your IP address) via cookies and processing this information by downloading this browser plugin and installing it: <b className='text-red-400'>https://tools.google.com/dlpage/gaoptout</b> 
</p>


<p className='text-gray-500 capitalize'>
Most web browsers allow some control of most cookies through the browser settings. To find out more about cookies, including how to see what cookies have been set and how to manage and delete them, visit www.allaboutcookies.org.
</p>

<b>How will we use the information we collect from you?</b>


<p className='text-gray-500 capitalize'>
     Information that we collect from you is used to process your order and to manage your account. We may also use your information to email you about other products or services that we think may be of interest to you.
</p>


<p className='text-gray-500 capitalize'>
In processing your order we may send your information to credit reference and fraud prevention agencies.     
</p>

<p className='text-gray-500 capitalize'>
  From time to time we may send your information to third parties which we consider may have goods or services which are of interest to you. If you do not wish to be contacted by third parties please reach out to us through our in-app customer support chat feature on Help Center.   
</p>

<b>
   Access to your information  
</b>

<p className='text-gray-500 capitalize'>
  You have a right to request a copy of the information we hold on you at any time. Please reach out to us through our in-app customer support chat feature on Help Center if you would like to receive a copy of this information. There will be a small charge for processing this request.   
</p>


<b>Fraud detection, prevention and security of our platform</b>


<p className='text-gray-500 capitalize'>
  In order to protect our customers and our platform from possible attacks, we continuously monitor the activities on our websites and mobile applications. To keep the platform secure and guarantee you a safe ordering experience, we use various technical measures to ensure that suspicious behavior patterns are detected at an early stage and prevented as early as possible. To achieve this goal, several software-based monitoring mechanisms run in parallel and prevent potential attackers from damaging our platform.   
</p>

<p className='text-gray-500 capitalize'>
    
The decision-making process is automated and could potentially have an impact on the use of your registered account on our platform. If any such decision leads to a negative result for you and you do not agree with the outcome, you can contact us via Help Center. In this case, we will individually assess the circumstances of your case. All of our fraud detection and prevention algorithms are always open to human review. If you think that a mistake has been made we are happy to look into it and make corrections, if necessary. 
</p>

<p className='text-gray-500 capitalize'>
  Categories of personal data: Location data Profile data (master data) Device information and access data Payment data Order data Voucher information   
</p>


<b>
     Other Websites
</b>

<p className='text-gray-500 capitalize pb-20'>
Our website may have links to other websites. This privacy policy only applies to this website. You should therefore read the privacy policies of the other websites when you are using those sites.    
</p>

</div>



               </div>   
          </div>
     )
}